// 自动生成的 stub —— 用真实实现替换
export type AgentToolProgress = any
export type BashProgress = any
export type MCPProgress = any
export type REPLToolProgress = any
export type SkillToolProgress = any
export type TaskOutputProgress = any
export type ToolProgressData = any
export type WebSearchProgress = any
export type ShellProgress = any
export type PowerShellProgress = any
export type SdkWorkflowProgress = any
