/**
 * 控制推理路由的环境变量：使用哪个 provider、访问哪个端点、发送哪些模型 ID。
 *
 * 当 spawn env 中 CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST 为真时，这些变量
 * 会从 settings 来源的 env 中剥离，防止用户的 ~/.hclaude/settings.json
 * 覆盖宿主机的路由配置——例如，针对终端 CLI 的 Bedrock 配置会破坏
 * 只支持 first-party 认证的宿主机。
 *
 * @[MODEL LAUNCH]: 新模型通常不需要在此处改动——
 * VERTEX_REGION_CLAUDE_* 采用前缀匹配。新 provider 或新的路由
 * 配置变量（endpoint、project、region、auth）才需要改动。
 *
 * 注意：OpenAI provider 使用 OPENAI_* 环境变量（OPENAI_API_KEY、OPENAI_BASE_URL、
 * OPENAI_MODEL、OPENAI_AUTH_MODE、OPENAI_DEFAULT_*_MODEL、OPENAI_SMALL_FAST_MODEL），
 * 这些均为 provider 管理变量，以便将路由配置与 Anthropic settings 隔离。
 */
const PROVIDER_MANAGED_ENV_VARS = new Set([
  // 标志本身——一旦宿主机设置，settings 不能取消它
  'CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST',
  // Provider 选择
  'CLAUDE_CODE_USE_BEDROCK',
  'CLAUDE_CODE_USE_VERTEX',
  'CLAUDE_CODE_USE_FOUNDRY',
  'CLAUDE_CODE_USE_GEMINI',
  // 端点配置（base URL、project/resource 标识符）
  'ANTHROPIC_BASE_URL',
  'ANTHROPIC_BEDROCK_BASE_URL',
  'ANTHROPIC_VERTEX_BASE_URL',
  'ANTHROPIC_FOUNDRY_BASE_URL',
  'ANTHROPIC_FOUNDRY_RESOURCE',
  'ANTHROPIC_VERTEX_PROJECT_ID',
  'GEMINI_BASE_URL',
  // 区域路由（每模型的 VERTEX_REGION_CLAUDE_* 通过下方前缀匹配处理）
  'CLOUD_ML_REGION',
  // 认证
  'ANTHROPIC_API_KEY',
  'ANTHROPIC_AUTH_TOKEN',
  'CLAUDE_CODE_OAUTH_TOKEN',
  'AWS_BEARER_TOKEN_BEDROCK',
  'ANTHROPIC_FOUNDRY_API_KEY',
  'CLAUDE_CODE_SKIP_BEDROCK_AUTH',
  'CLAUDE_CODE_SKIP_VERTEX_AUTH',
  'CLAUDE_CODE_SKIP_FOUNDRY_AUTH',
  'GEMINI_API_KEY',
  // 模型默认值——通常设置为 provider 特定的 ID 格式
  'ANTHROPIC_MODEL',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'ANTHROPIC_DEFAULT_OPUS_MODEL',
  'ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'ANTHROPIC_DEFAULT_OPUS_MODEL_NAME',
  'ANTHROPIC_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'ANTHROPIC_DEFAULT_SONNET_MODEL',
  'ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'ANTHROPIC_DEFAULT_SONNET_MODEL_NAME',
  'ANTHROPIC_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
  // OpenAI provider 专用
  'OPENAI_AUTH_MODE',
  'OPENAI_API_KEY',
  'OPENAI_BASE_URL',
  'OPENAI_MODEL',
  'OPENAI_DEFAULT_HAIKU_MODEL',
  'OPENAI_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'OPENAI_DEFAULT_HAIKU_MODEL_NAME',
  'OPENAI_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'OPENAI_DEFAULT_OPUS_MODEL',
  'OPENAI_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'OPENAI_DEFAULT_OPUS_MODEL_NAME',
  'OPENAI_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'OPENAI_DEFAULT_SONNET_MODEL',
  'OPENAI_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'OPENAI_DEFAULT_SONNET_MODEL_NAME',
  'OPENAI_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
  'OPENAI_SMALL_FAST_MODEL',
  'ANTHROPIC_SMALL_FAST_MODEL',
  'ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION',
  'CLAUDE_CODE_SUBAGENT_MODEL',
  'GEMINI_MODEL',
  'GEMINI_SMALL_FAST_MODEL',
  // Gemini provider 专用——与 Anthropic/OpenAI 独立
  'GEMINI_DEFAULT_HAIKU_MODEL',
  'GEMINI_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'GEMINI_DEFAULT_HAIKU_MODEL_NAME',
  'GEMINI_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'GEMINI_DEFAULT_OPUS_MODEL',
  'GEMINI_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'GEMINI_DEFAULT_OPUS_MODEL_NAME',
  'GEMINI_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'GEMINI_DEFAULT_SONNET_MODEL',
  'GEMINI_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'GEMINI_DEFAULT_SONNET_MODEL_NAME',
  'GEMINI_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
])

const PROVIDER_MANAGED_ENV_PREFIXES = [
  // 每模型 Vertex 区域覆盖——随模型发布扩展，因此
  // 使用前缀匹配以避免每次发布时产生漂移。
  'VERTEX_REGION_CLAUDE_',
]

export function isProviderManagedEnvVar(key: string): boolean {
  const upper = key.toUpperCase()
  return (
    PROVIDER_MANAGED_ENV_VARS.has(upper) ||
    PROVIDER_MANAGED_ENV_PREFIXES.some(p => upper.startsWith(p))
  )
}

/**
 * 可执行任意 shell 代码的危险 shell 设置项
 */
export const DANGEROUS_SHELL_SETTINGS = [
  'apiKeyHelper',
  'awsAuthRefresh',
  'awsCredentialExport',
  'gcpAuthRefresh',
  'otelHeadersHelper',
  'statusLine',
] as const

/**
 * 可在信任对话框之前应用的安全环境变量。
 * 这些是 Claude Code 专属设置，不存在安全风险。
 *
 * 重要：这是判断哪些 env var 安全的唯一可信来源。
 * 不在此列表中的 env var 均视为危险，通过远程托管 settings 设置时
 * 会触发安全对话框。
 *
 * 危险 env var（不在此列表中）：
 *
 * === 重定向到攻击者控制的服务器 ===
 * - ANTHROPIC_BASE_URL, ANTHROPIC_BEDROCK_BASE_URL, ANTHROPIC_FOUNDRY_BASE_URL, ANTHROPIC_VERTEX_BASE_URL
 * - HTTP_PROXY, HTTPS_PROXY, NO_PROXY, http_proxy, https_proxy, no_proxy
 * - OTEL_EXPORTER_OTLP_ENDPOINT, OTEL_EXPORTER_OTLP_LOGS_ENDPOINT, OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
 *
 * === 信任攻击者控制的服务器 ===
 * - NODE_TLS_REJECT_UNAUTHORIZED
 * - NODE_EXTRA_CA_CERTS
 *
 * === 切换到攻击者控制的项目 ===
 * - ANTHROPIC_FOUNDRY_RESOURCE
 * - ANTHROPIC_API_KEY, ANTHROPIC_AUTH_TOKEN
 * - AWS_BEARER_TOKEN_BEDROCK
 */
export const SAFE_ENV_VARS = new Set([
  'ANTHROPIC_CUSTOM_HEADERS',
  'ANTHROPIC_CUSTOM_MODEL_OPTION',
  'ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION',
  'ANTHROPIC_CUSTOM_MODEL_OPTION_NAME',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'ANTHROPIC_DEFAULT_OPUS_MODEL',
  'ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'ANTHROPIC_DEFAULT_OPUS_MODEL_NAME',
  'ANTHROPIC_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'ANTHROPIC_DEFAULT_SONNET_MODEL',
  'ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'ANTHROPIC_DEFAULT_SONNET_MODEL_NAME',
  'ANTHROPIC_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
  // OpenAI provider 专用
  'OPENAI_API_KEY',
  'OPENAI_AUTH_MODE',
  'OPENAI_BASE_URL',
  'OPENAI_DEFAULT_HAIKU_MODEL',
  'OPENAI_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'OPENAI_DEFAULT_HAIKU_MODEL_NAME',
  'OPENAI_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'OPENAI_DEFAULT_OPUS_MODEL',
  'OPENAI_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'OPENAI_DEFAULT_OPUS_MODEL_NAME',
  'OPENAI_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'OPENAI_DEFAULT_SONNET_MODEL',
  'OPENAI_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'OPENAI_DEFAULT_SONNET_MODEL_NAME',
  'OPENAI_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
  'OPENAI_ENABLE_THINKING',
  'OPENAI_MAX_TOKENS',
  'OPENAI_MODEL',
  'OPENAI_ORG_ID',
  'OPENAI_PROJECT_ID',
  'OPENAI_SMALL_FAST_MODEL',
  // Grok provider 专用
  'GROK_API_KEY',
  'GROK_BASE_URL',
  'GROK_DEFAULT_HAIKU_MODEL',
  'GROK_DEFAULT_OPUS_MODEL',
  'GROK_DEFAULT_SONNET_MODEL',
  'GROK_MODEL',
  'GROK_MODEL_MAP',
  'XAI_API_KEY',
  'ANTHROPIC_FOUNDRY_API_KEY',
  'ANTHROPIC_MODEL',
  'ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION',
  'ANTHROPIC_SMALL_FAST_MODEL',
  'AWS_DEFAULT_REGION',
  'AWS_PROFILE',
  'AWS_REGION',
  'BASH_DEFAULT_TIMEOUT_MS',
  'BASH_MAX_OUTPUT_LENGTH',
  'BASH_MAX_TIMEOUT_MS',
  'CLAUDE_BASH_MAINTAIN_PROJECT_WORKING_DIR',
  'CLAUDE_CODE_API_KEY_HELPER_TTL_MS',
  'CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS',
  'CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC',
  'CLAUDE_CODE_DISABLE_TERMINAL_TITLE',
  'CLAUDE_CODE_ENABLE_TELEMETRY',
  'CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS',
  'CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL',
  'CLAUDE_CODE_MAX_OUTPUT_TOKENS',
  'CLAUDE_CODE_SKIP_BEDROCK_AUTH',
  'CLAUDE_CODE_SKIP_FOUNDRY_AUTH',
  'CLAUDE_CODE_SKIP_VERTEX_AUTH',
  'CLAUDE_CODE_SUBAGENT_MODEL',
  'CLAUDE_CODE_USE_BEDROCK',
  'CLAUDE_CODE_USE_FOUNDRY',
  'CLAUDE_CODE_USE_GEMINI',
  'CLAUDE_CODE_USE_GROK',
  'CLAUDE_CODE_USE_OPENAI',
  'CLAUDE_CODE_USE_VERTEX',
  'GEMINI_API_KEY',
  'GEMINI_BASE_URL',
  'GEMINI_MODEL',
  'GEMINI_SMALL_FAST_MODEL',
  'GEMINI_DEFAULT_HAIKU_MODEL',
  'GEMINI_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'GEMINI_DEFAULT_HAIKU_MODEL_NAME',
  'GEMINI_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'GEMINI_DEFAULT_OPUS_MODEL',
  'GEMINI_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'GEMINI_DEFAULT_OPUS_MODEL_NAME',
  'GEMINI_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'GEMINI_DEFAULT_SONNET_MODEL',
  'GEMINI_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'GEMINI_DEFAULT_SONNET_MODEL_NAME',
  'GEMINI_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
  'DISABLE_AUTOUPDATER',
  'DISABLE_BUG_COMMAND',
  'DISABLE_COST_WARNINGS',
  'DISABLE_ERROR_REPORTING',
  'DISABLE_FEEDBACK_COMMAND',
  'DISABLE_TELEMETRY',
  'ENABLE_SEARCH_EXTRA_TOOLS',
  'MAX_MCP_OUTPUT_TOKENS',
  'MAX_THINKING_TOKENS',
  'MCP_TIMEOUT',
  'MCP_TOOL_TIMEOUT',
  'OTEL_EXPORTER_OTLP_HEADERS',
  'OTEL_EXPORTER_OTLP_LOGS_HEADERS',
  'OTEL_EXPORTER_OTLP_LOGS_PROTOCOL',
  'OTEL_EXPORTER_OTLP_METRICS_CLIENT_CERTIFICATE',
  'OTEL_EXPORTER_OTLP_METRICS_CLIENT_KEY',
  'OTEL_EXPORTER_OTLP_METRICS_HEADERS',
  'OTEL_EXPORTER_OTLP_METRICS_PROTOCOL',
  'OTEL_EXPORTER_OTLP_PROTOCOL',
  'OTEL_EXPORTER_OTLP_TRACES_HEADERS',
  'OTEL_LOG_TOOL_DETAILS',
  'OTEL_LOG_USER_PROMPTS',
  'OTEL_LOGS_EXPORT_INTERVAL',
  'OTEL_LOGS_EXPORTER',
  'OTEL_METRIC_EXPORT_INTERVAL',
  'OTEL_METRICS_EXPORTER',
  'OTEL_METRICS_INCLUDE_ACCOUNT_UUID',
  'OTEL_METRICS_INCLUDE_SESSION_ID',
  'OTEL_METRICS_INCLUDE_VERSION',
  'OTEL_RESOURCE_ATTRIBUTES',
  'USE_BUILTIN_RIPGREP',
  'VERTEX_REGION_CLAUDE_3_5_HAIKU',
  'VERTEX_REGION_CLAUDE_3_5_SONNET',
  'VERTEX_REGION_CLAUDE_3_7_SONNET',
  'VERTEX_REGION_CLAUDE_4_0_OPUS',
  'VERTEX_REGION_CLAUDE_4_0_SONNET',
  'VERTEX_REGION_CLAUDE_4_1_OPUS',
  'VERTEX_REGION_CLAUDE_4_5_SONNET',
  'VERTEX_REGION_CLAUDE_4_6_SONNET',
  'VERTEX_REGION_CLAUDE_HAIKU_4_5',
])
